---
- name: Converge
  hosts: all
  become: true

  vars:
    mgr_telegraf:
      address: udp://172.16.3.12:8094
      interval: 60

  roles:
    - role: ansible-role-ceph-mgr-telegraf

  post_tasks:
    - name: Give Ceph time to work
      pause: seconds=5

    - name: Verify the telegraf config address was set
      command: >-
        {{ container_exec_cmd | default('') }}
        ceph
        --connect-timeout 5
        --cluster {{ cluster }}
        telegraf config-show
        -f json
      changed_when: false
      delegate_to: "{{ groups[mon_group_name][0] }}"
      register: telegraf_config_show
      run_once: true
      failed_when: (telegraf_config_show.stdout | from_json).address != 'udp://172.16.3.12:8094'

    - name: Check ceph health
      command: >-
        {{ container_exec_cmd | default('') }}
        ceph
        --connect-timeout 5
        --cluster {{ cluster }}
        health
      changed_when: false
      delegate_to: "{{ groups[mon_group_name][0] }}"
      register: ceph_health
      until: ceph_health is succeeded
      run_once: true
      failed_when: "'HEALTH_OK' not in ceph_health.stdout"
